services:
  - type: web
    name: birthday-love-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: ADMIN_KEY
        sync: false
